permalink: /posts/:title/
show_excerpts: true
baseurl: ""
sass:
  sass_dir: _sass

texture:
  style: [black]
  title: Handong's Blog
  date_format: "%b %-d, %Y"
  tagline: e-mail:ritnis4751@kookmin.ac.kr

  
  social_links:
    github: ritnis4751
    rss: what is this?
# Build settings
# theme: texture
plugins:
  - jekyll-seo-tag


ins:
  - jekyll-seo-tag
#  - jekyll-feed