title: Handong's Blog
author: Son Handong
email: ritnis4751@kookmin.ac.kr

show_excerpts: true
baseurl: ""
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Handong's Blog
  tagline: e-mail:ritnis4751@kookmin.ac.kr
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: true

  social_links:
    github: ritnis4751
# Build settings
# theme: texture
plugins:
  - jekyll-seo-tag

#  - jekyll-feed